watch:
	npx @marp-team/marp-cli -w slides.md

html:
	npx @marp-team/marp-cli slides.md

pdf:	## Convert slide deck into PDF
	npx @marp-team/marp-cli slides.md --allow-local-files --pdf

ppt:	## Convert slide deck into PowerPoint document (PPTX)
	npx @marp-team/marp-cli slides.md --allow-local-files --pptx
