watch:
	npx @marp-team/marp-cli -w index.md

html:
	npx @marp-team/marp-cli index.md

pdf:	## Convert slide deck into PDF
	npx @marp-team/marp-cli index.md --allow-local-files --pdf

ppt:	## Convert slide deck into PowerPoint document (PPTX)
	npx @marp-team/marp-cli index.md --allow-local-files --pptx
